# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Insomnius Playground
email: awc.aliana@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a software engineer based on Jakarta, Indonesia. I used to write my code in Golang, Ruby or PHP.
  I believe good technology is not the one with all of complex science inside it, but the one who make good impact
  for others and develop a bonds between the user and the maker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: insomnius_
github_username:  inisomnius
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
logo: "https://s.gravatar.com/avatar/77125555f2b03f5ed50547842a87ef0f" # Site logo, also used in jekyll-seo-tag
image: "https://avatars1.githubusercontent.com/u/20650401"
repo: "https://github.com/insomnius"
disqus: "insomnius-18" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://s.gravatar.com/avatar/77125555f2b03f5ed50547842a87ef0f" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
service_worker: true # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Build settings
markdown: kramdown
theme: alembic-jekyll-theme
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji

paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: insomnius_ # jekyll-seo-tag > Owners twitter username
author: Insomnius # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Insomnius # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/insomnius_
    - https://www.linkedin.com/in/insomnius
    - https://github.com/insomnius

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Jakarta # Timezone for blog posts and alike

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

defaults:
  -
    scope:
      path: "/"
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""

navigation_header:
  Home: /
  About: /about/
  Categories: /categories/

navigation_footer:
  About: /about/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
